using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using MvvmCross.Droid.Views;
namespace BusinessApp.Droid
{
    [Activity(Label = "RegisterActivity")]
    public class RegisterActivity : MvxActivity
    {
        protected override void OnViewModelSet()
        {
            // This uses a resource identifier generated by Android to identify the view.
            SetContentView(Resource.Layout.Register);
        }
    }
}